name: linter
on: # trigger
  workflow_dispatch: {} # manual trigger
  pull_request:
    branches: [main] # on pull request that targets the main branch, tribber this workflow

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          set-safe-directory: tru

      - name: run linting Cchecks
        run: |
