name: sqlfluff_linter
on: # trigger
  pull_request:
    branches: main
jobs:
  SQLFluff_linter:
    runs-on: ubuntu-latest #will create an Ubuntu VM to run the action on
    environment: earthquake_project

    steps:
      - name: Checkout code #this pulls the repo into your runner
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install dbt-snowflake sqlfluff sqlfluff-templater-dbt

      - name: Install dbt packages
        working-directory: transform/dbt/earthquake
        run: |
          dbt deps

      - name: Run SQLFluff lint
        working-directory: transform/dbt/earthquake
        env:
          # Secrets (from GitHub Environment: earthquake_project)
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

          # Variables (from GitHub Environment: earthquake_project)
          SNOWFLAKE_ROLE: ${{ vars.SNOWFLAKE_ROLE }}
          SNOWFLAKE_DATABASE: ${{ vars.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_WAREHOUSE: ${{ vars.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_SCHEMA: ${{ vars.SNOWFLAKE_SCHEMA }}
          DBT_TARGET: dev
        run: |
          sqlfluff lint models
