name: linter
on: # trigger
  pull_request:
    branches: [main]
jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        -name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install dbt-snowflake sqlfluff sqlfluff-templater-dbt

      - name: Install dbt packages
        working-directory: transform/dbt/earthquake
        run: |
          dbt deps

      - name: Run SQLFluff lint
        working-directory: transform/dbt/earthquake
        env:
          DBT_PROFILES_DIR: ~/.dbt
        run: |
          sqlfluff lint models